ucsb-cs156-f24/team02-f24-16

src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBRecommendationRequest.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBRecommendationRequestRepository.java, src/main/resources/db/migration/changes/RecommendationRequest.json, src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java
copied over files from team01 recommendationRequest
closes #26
=> copied over files from team01 recommendationRequest

src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java, src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItem.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java
Copied files from team01 and tested on my own dokku app that swagger endpoints appear
=> copied files from team01

src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java, src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java, src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java, src/main/resources/db/migration/changes/UCSBOrganization.json, src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java
=> added team01 organization files

frontend/src/fixtures/ucsbOrganizationFixtures.js
=> added fixtures

frontend/src/fixtures/ucsbDiningCommonsMenuItemFixtures.js
hopefully this fixture file works
=> Kl ucsbdiningcommonsmenuitem fixture

frontend/src/fixtures/helpRequestFixtures.js
Fixtures for helprequest table have been set! Closes #45 🌟
=> HelpRequest fixtures have been set!

frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js
This pull implements the recommendation request form and testing.
closes #28
=> Rec Req form and testing suite implemented

frontend/src/main/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.js, frontend/src/stories/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.stories.js, frontend/src/tests/components/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemForm.test.js
created ucsbdiningcommonsmenuitem form, form test, and form story
link to storybook: https://672461c4d180463107c908c5-pbcvanopaw.chromatic.com/?path=/docs/components-ucsbdiningcommonsmenuitem-ucsbdiningcommonsmenuitemform--docs
=> form, story, test for ucsbdiningcommonsmenuitem

frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js, frontend/src/main/utils/recommendationRequestUtils.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestForm.stories.js, frontend/src/stories/components/RecommendationRequest/RecommendationRequestTable.stories.js, frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js, frontend/src/tests/utils/RecommendationRequestUtils.test.js
Implemented the Recommendation Request react table. 
I also found a way to visualise the boolean values in the table with a "check" or a "x". 
Once merged, can someone link directly to the story
for the new RecommendationRequestTable component.
The criteria for this states that we must have a link to the story-board for the Recommendation Request, but its not possible to link without the code being merged ...
closes #29
=> Recommendation Request react table and tests.

src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewController.java, src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java, src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java, src/main/resources/db/migration/changes/MenuItemReview.json, src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewControllerTests.java
=> Copied files for backend CRUD API

frontend/src/fixtures/menuItemReviewFixtures.js
=> Created Fixtures for MenuItemReview table

frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js, frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js, frontend/src/main/utils/ucsbOrganizationUtils.js, frontend/src/stories/components/UCSBOrganization/UCSBOrganizationTable.stories.js, frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js, frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js, frontend/src/tests/utils/UCSBOrganizationTableUtils.test.js
=> Table component for organizations #20

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js, frontend/src/tests/components/Nav/AppNavbar.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js
UCSB Dining Commons Menu appears on the navigation bar
=> added UCSB Dining Commons Menu Item onto the navigation bar

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js, frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js, frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js, frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js, frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js, frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js
=> Copied placeholders for organizations #21

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js, frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js, frontend/src/stories/pages/RecommendationRequest/RecommendationRequestCreatePage.stories.js, frontend/src/tests/components/Nav/AppNavbar.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js, frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js
To test the code, 
* Navigate to the page at ex <https://team02-dev-jayster7101.dokku-16.cs.ucsb.edu> /recommendationRequest/create 
* Then fill out each of the required forms and press the Create button
* This will add a new recommendation request to the database
* It will also pop up and show you the successful request
Screenshots:
*Blank screen on navigate*
*Errors for bad input*
*Full input with valid input*
*successful request to server*
Closes #31
=> Recommendation Request Create Page, tests, and story book.

frontend/src/main/pages/Articles/ArticlesCreatePage.js, frontend/src/tests/pages/Articles/ArticlesCreatePage.test.js
https://www.chromatic.com/build?appId=672461c4d180463107c908c5&number=118
=> sa-implemented articles create page with tests

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/tests/components/Nav/AppNavbar.test.js
=> Fixing merge, recommendation Request 

frontend/src/main/pages/Articles/ArticlesIndexPage.js, frontend/src/stories/pages/Articles/ArticlesCreatePage.stories.js, frontend/src/stories/pages/Articles/ArticlesIndexPage.stories.js, frontend/src/tests/pages/Articles/ArticlesIndexPage.test.js
https://672461c4d180463107c908c5-edsftmhneb.chromatic.com/?path=/story/pages-articles-articlesindexpage--three-items-admin-user
=> sa-implemented index page for articles and tested

frontend/src/fixtures/menuItemReviewFixtures.js, frontend/src/main/components/MenuItemReview/MenuItemReviewForm.js, frontend/src/stories/components/MenuItemReview/MenuItemReviewForm.stories.js, frontend/src/tests/components/MenuItemReview/MenuItemReviewForm.test.js, src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewController.java, src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java, src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java, src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewControllerTests.java
Closes #37 
In this PR, we add a form for the Commits table.
This only adds the form to the storybook; it is not yet integrated into the app.
To access the storybook, use this link: https://672461c4d180463107c908c5-chpwypyxuu.chromatic.com/?path=/docs/components-articles-articlesform--docs
=> MenuItemReviewForm completed

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js, frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js, frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js, frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js, frontend/src/main/utils/ucsbOrganizationUtils.js, frontend/src/stories/components/UCSBOrganization/UCSBOrganizationTable.stories.js, frontend/src/stories/pages/UBCSOrganization.js/UCSBOrganizationCreatePage.stories.js, frontend/src/stories/pages/UBCSOrganization.js/UCSBOrganizationIndexPage.stories.js, frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js, frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js, frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js, frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js, frontend/src/tests/utils/UCSBOrganizationTableUtils.test.js, src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java, src/main/resources/db/migration/changes/UCSBOrganization.json
Closes #22 #23
storybook link: https://672461c4d180463107c908c5-dvlnldqzti.chromatic.com/?path=/docs/pages-ucsborganization-ucsborganizationindexpage--docs
=> organizations index page and create page

frontend/src/App.js, frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js, frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.stories.js, frontend/src/tests/components/Nav/AppNavbar.test.js, frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js
Created and implemented all the files for the edit page for UCSB dining commons menu item, also added UCSB dining commons menu item to the App.js file and the AppNavBar.test.
testing link: https://team02-li-kelly-dev.dokku-16.cs.ucsb.edu/
storybook link: https://672461c4d180463107c908c5-ihxpqsnvih.chromatic.com/?path=/docs/pages-ucsbdiningcommonsmenuitem-ucsbdiningcommonsmenuitemeditpage--docs
Closes #15
=> Created the edit page for UCSB dining commons menu item

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js, frontend/src/stories/pages/UBCSOrganization.js/UCSBOrganizationEditPage.stories.js, frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js, frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js, src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java, src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java
Closes #24 
Storybook link: https://672461c4d180463107c908c5-oufioojcjy.chromatic.com/?path=/docs/pages-ucsborganization-ucsborganizationeditpage--docs
=> Added edit page for organizations

frontend/src/main/pages/Articles/ArticlesEditPage.js, frontend/src/stories/pages/Articles/ArticlesEditPage.stories.js, frontend/src/tests/pages/Articles/ArticlesEditPage.test.js
=> sa-implemented edit page for articles and tested

frontend/src/fixtures/helpRequestFixtures.js, frontend/src/main/components/HelpRequest/HelpRequestForm.js, frontend/src/main/components/HelpRequest/HelpRequestTable.js, frontend/src/main/utils/HelpRequestUtils.js, frontend/src/stories/components/HelpRequest/HelpRequestForm.stories.js, frontend/src/stories/components/HelpRequest/HelpRequestTable.stories.js, frontend/src/tests/components/HelpRequest/HelpRequestForm.test.js, frontend/src/tests/components/HelpRequest/HelpRequestTable.test.js, frontend/src/tests/utils/HelpRequestUtils.test.js
Both HelpRequest form and table components have been implemented, with mutation and coverage tests passing 🌟 
Images below show the form and table as they should appear! Closes #46 and #47.
**Chromatic Build Link** ; [LINK](https://www.chromatic.com/build?appId=672461c4d180463107c908c5&number=158)
**Form** ; [LINK](https://672461c4d180463107c908c5-keqrhxiepa.chromatic.com/?path=/docs/components-helprequest-helprequestform--docs)
**Table** ; [LINK](https://672461c4d180463107c908c5-keqrhxiepa.chromatic.com/?path=/docs/components-helprequest-helprequesttable--docs)
**Create Form**
**Update Form**
**Empty Table**
**Table for Admin**
**Table for Regular User**
=> HelpRequest Form + Table Components Implementation

frontend/src/main/components/Nav/AppNavbar.js
Part of the separate pull request ; Added HelpRequest page route for the navigation bar.
=> Update AppNavbar.js with HelpRequest page!

frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js, frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js, frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js, frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js, frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js, frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js
Due to merge conflicts for App.js and AppNavbar.js, I'll be doing separate pull requests to add HelpRequest to the code. I hope that's alright? 
Placeholder implementation for HelpRequest!
Closes #48 !
**App.js** ; https://github.com/ucsb-cs156-f24/team02-f24-16/pull/107
**AppNavBar.js** ; https://github.com/ucsb-cs156-f24/team02-f24-16/pull/106
**HelpRequest Index page with entries**
**HelpRequest Edit page**
**HelpRequest Create page**
=> HelpRequest placeholder pages implemented!

frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js, frontend/src/stories/pages/HelpRequest/HelpRequestEditPage.stories.js, frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js
Closes #51 !
Implements the Edit Page for HelpRequest!
**Storybook Link** ; DRAFT
**Original Entry**
**Entry Changed**
**Wrong Entries with Errors**
=> HelpRequest Edit Page Implementation!

src/test/java/edu/ucsb/cs156/example/integration/UCSBOrganizationIT.java
Team03 integration test implemented for UCSBOrganization
=> Added Integration Test for UCSBOrganization

src/test/java/edu/ucsb/cs156/example/integration/ArticlesIT.java
This implements two integration tests for the articles controller endpoint.
This is part of team03
Closes #116
=> Sa articles integration tests

src/test/java/edu/ucsb/cs156/example/integration/UCSBDiningCommonsMenuItemIT.java, src/test/java/edu/ucsb/cs156/example/web/UCSBDiningCommonsMenuItemWebIT.java
Part of Team03
Followed the video example and RestaurantIT.java and created two integrations tests for UCSBDiningCommonsMenuItem.
Also added the end to end test of "admin can create/edit/delete" for UCSBDiningCommonsMenuItem.
=> Added the integration and end to end tests for UCSBDiningCommonsMenuItem

src/test/java/edu/ucsb/cs156/example/web/ArticlesWebIT.java
This implements two E2E tests for articles. 
This is part of team03.
Closes #115
=> sa - implemented E2E testing for articles

src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewControllerTests.java, src/test/java/edu/ucsb/cs156/example/integration/MenuItemReviewIT.java
In this PR, we add two integration tests for the MenuItemReview table.
This is part of the team03 assignment. Closes #132
=> Integration tests added for MenuItemReview

src/test/java/edu/ucsb/cs156/example/web/MenuItemReviewWebIT.java
Closes #133 
In this PR, we add end2end tests for MenuItemReview
=> Added e2e tests for MenuItemReview Table
